# Generated by Django 6.0.7 on 2026-08-04 03:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('park', 'Park'), ('campground', 'Campground'), ('trail', 'Trail'), ('boat_launch', 'Boat Launch'), ('scenic_overlook', 'Scenic Overlook'), ('beach', 'Beach'), ('cabin', 'Cabin'), ('backyard', 'Backyard'), ('summit', 'Summit'), ('island', 'Island'), ('rest_area', 'Rest Area'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adventures', to='core.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.adventure')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('body', models.TextField()),
                ('entry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('radio', models.CharField(blank=True, max_length=150)),
                ('antenna', models.CharField(blank=True, max_length=150)),
                ('equipment_description', models.TextField(blank=True)),
                ('qrp', models.BooleanField(default=False)),
                ('pota', models.BooleanField(default=False)),
                ('other_operating_method', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.adventure')),
            ],
            options={
                'ordering': ['entry_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('parking', models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10)),
                ('restrooms', models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10)),
                ('picnic_tables', models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10)),
                ('shelter', models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10)),
                ('shade', models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10)),
                ('power', models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10)),
                ('drinking_water', models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10)),
                ('cell_coverage_bars', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, '1 Bar'), (2, '2 Bars'), (3, '3 Bars'), (4, '4 Bars'), (5, '5 Bars')], default=0)),
                ('ambient_noise_level', models.CharField(choices=[('unknown', 'Unknown'), ('very_quiet', 'Very Quiet'), ('quiet', 'Quiet'), ('moderate', 'Moderate'), ('busy', 'Busy'), ('very_busy', 'Very Busy')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_locations', to='core.location')),
            ],
            options={
                'ordering': ['location__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='adventure',
            name='operating_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adventures', to='core.operatinglocation'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='adventure_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('review', 'Needs Review'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.journalentry')),
            ],
            options={
                'ordering': ['taken_at', 'display_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='adventure',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_adventures', to='core.photo'),
        ),
        migrations.AddConstraint(
            model_name='operatinglocation',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_operating_location_name_per_location'),
        ),
    ]
