# Generated by Django 6.0.7 on 2026-08-05 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_adventure_journal_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(blank=True, max_length=20, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('home_city', models.CharField(blank=True, max_length=100)),
                ('home_state', models.CharField(blank=True, max_length=80)),
                ('home_country', models.CharField(default='USA', max_length=80)),
                ('website', models.URLField(blank=True)),
                ('profile_is_public', models.BooleanField(default=True)),
                ('callsign_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_member_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['callsign'],
            },
        ),
    ]
