# Generated by Django 6.0.7 on 2026-08-06 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_member_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='qrz_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='qrz_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='qrz_expiration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='qrz_first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='qrz_grid',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='qrz_last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='qrz_license_class',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='qrz_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='qrz_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MemberCallsignAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_callsign', models.CharField(max_length=20)),
                ('new_callsign', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callsign_audits', to='core.memberprofile')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
