# Generated by Django 6.0.7 on 2026-08-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_follower_invitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='advisory_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='has_operating_advisory',
            field=models.BooleanField(default=False, help_text='Show this Location with a red map pin.'),
        ),
        migrations.AddField(
            model_name='location',
            name='operating_advisory',
            field=models.TextField(blank=True, help_text='What should another operator know before making the trip?'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='email_visible_to_members',
            field=models.BooleanField(default=True, help_text='Show my email address to signed-in Radio Outdoors Members.'),
        ),
    ]
