# Generated by Django 6.0.7 on 2026-08-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_location_wma_dnr_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='email_visible_to_members',
            field=models.BooleanField(default=False, help_text='Show my email address to signed-in Radio Outdoors Members.'),
        ),
    ]
