# Generated by Django 6.0.7 on 2026-08-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_memberprofile_email_visible_to_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='member_profiles/%Y/%m/'),
        ),
    ]
