# Generated by Django 6.0.7 on 2026-08-07 17:30

from django.db import migrations, models


def preserve_existing_verification(apps, schema_editor):
    MemberProfile = apps.get_model("core", "MemberProfile")
    for profile in MemberProfile.objects.filter(callsign_verified=True).iterator():
        profile.verification_method = "qrz"
        profile.verification_at = profile.qrz_verified_at or profile.updated_at
        profile.save(
            update_fields=["verification_method", "verification_at"]
        )


def clear_verification_method(apps, schema_editor):
    MemberProfile = apps.get_model("core", "MemberProfile")
    MemberProfile.objects.update(
        verification_method="none",
        verification_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_member_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='verification_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='verification_method',
            field=models.CharField(choices=[('none', 'Not Verified'), ('qrz', 'QRZ Verified'), ('admin', 'Admin Verified'), ('development', 'Development Only')], db_index=True, default='none', max_length=12),
        ),
        migrations.RunPython(
            preserve_existing_verification,
            clear_verification_method,
        ),
    ]
