# Generated by Django 6.0.7 on 2026-08-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_defaultlocationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='status',
            field=models.CharField(choices=[('active', 'Open'), ('completed', 'Complete')], default='active', max_length=12),
        ),
    ]
