# Generated by Django 6.0.7 on 2026-08-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_requeue_existing_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultlocationimage',
            name='moderation_provider',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='defaultlocationimage',
            name='moderation_provider_model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='location',
            name='photo_moderation_provider',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='location',
            name='photo_moderation_provider_model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profile_photo_moderation_provider',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profile_photo_moderation_provider_model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='photo',
            name='moderation_provider',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='photo',
            name='moderation_provider_model',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
