# Generated by Django 6.0.7 on 2026-08-08 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_moderation_provider_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultlocationimage',
            name='automated_decision',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='location',
            name='photo_automated_decision',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profile_photo_automated_decision',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='PhotoModerationActionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=16)),
                ('decision_source', models.CharField(max_length=40)),
                ('scope', models.CharField(max_length=32)),
                ('requested_target_ids', models.JSONField(default=list)),
                ('successful_target_ids', models.JSONField(default=list)),
                ('failed_targets', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
