# Generated by Django 6.0.7 on 2026-08-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_photo_moderation_bulk_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultlocationimage',
            name='rejection_explanation',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='defaultlocationimage',
            name='rejection_reason_code',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='location',
            name='photo_rejection_explanation',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='location',
            name='photo_rejection_reason_code',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profile_photo_rejection_explanation',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profile_photo_rejection_reason_code',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='photo',
            name='rejection_explanation',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='photo',
            name='rejection_reason_code',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
