# Generated by Django 6.0.7 on 2026-08-09 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_photo_moderation_rejection_reasons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantinedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_kind', models.CharField(choices=[('photo', 'Adventure or Journal photo'), ('location', 'Location photo'), ('profile', 'Member profile photo'), ('default', 'Default Location image')], max_length=16)),
                ('original_object_id', models.PositiveBigIntegerField()),
                ('original_target', models.CharField(db_index=True, max_length=48)),
                ('association_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('association_label', models.CharField(max_length=320)),
                ('image', models.FileField(max_length=500, upload_to='photo_quarantine/')),
                ('metadata', models.JSONField(default=dict)),
                ('removal_reason', models.CharField(max_length=48)),
                ('removal_explanation', models.CharField(blank=True, max_length=240)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('removed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarantined_photos', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_quarantined_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-removed_at'],
            },
        ),
    ]
