# Generated by Django 6.0.7 on 2026-08-09 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def infer_existing_creators(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    OperatingLocation = apps.get_model("core", "OperatingLocation")
    for location in Location.objects.all().iterator():
        owner_ids = list(
            location.adventures.order_by().values_list("owner_id", flat=True).distinct()[:2]
        )
        if len(owner_ids) == 1:
            location.created_by_id = owner_ids[0]
            location.save(update_fields=["created_by"])
    for position in OperatingLocation.objects.select_related("location").iterator():
        owner_ids = list(
            position.adventures.order_by().values_list("owner_id", flat=True).distinct()[:2]
        )
        if len(owner_ids) == 1:
            position.created_by_id = owner_ids[0]
        elif not owner_ids and position.location.created_by_id:
            position.created_by_id = position.location.created_by_id
        if position.created_by_id:
            position.save(update_fields=["created_by"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_quarantinedphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatinglocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operating_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(infer_existing_creators, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CoordinateChangeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=24)),
                ('record_id', models.PositiveBigIntegerField()),
                ('previous_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('previous_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('new_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('new_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinate_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
