# Generated by Django 6.0.7 on 2026-08-09 02:31

from django.db import migrations, models
from pathlib import PurePosixPath


def populate_photo_references(apps, schema_editor):
    Photo = apps.get_model("core", "Photo")
    photos = list(Photo.objects.all().only("id", "image", "reference_number", "original_filename"))
    for photo in photos:
        photo.reference_number = f"RO-PH-{photo.pk:06d}"
        photo.original_filename = PurePosixPath(photo.image.name).name[:255]
    if photos:
        Photo.objects.bulk_update(photos, ["reference_number", "original_filename"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_location_created_by_operatinglocation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='derivative_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='photo',
            name='derivative_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='photo',
            name='moderation_image',
            field=models.ImageField(blank=True, upload_to='photo_derivatives/moderation/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='original_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='photo',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='photo_derivatives/thumbnails/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='web_image',
            field=models.ImageField(blank=True, upload_to='photo_derivatives/web/'),
        ),
        migrations.AddField(
            model_name='photomoderationactionaudit',
            name='target_references',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(populate_photo_references, migrations.RunPython.noop),
    ]
