# Generated by Django 6.0.7 on 2026-08-09 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_photo_derivative_metadata_photo_derivative_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_identifier', models.CharField(max_length=254)),
                ('terms_version', models.CharField(max_length=40)),
                ('privacy_version', models.CharField(max_length=40)),
                ('community_version', models.CharField(max_length=40)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('registration_path', models.CharField(max_length=40)),
                ('age_attested', models.BooleanField()),
                ('account_status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'terms_version', 'privacy_version', 'community_version'), name='unique_policy_bundle_per_user')],
            },
        ),
    ]
