from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [("core", "0040_journalcontact_geography_and_radio_fields"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="PotaImportBatch", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("confirmed_at", models.DateTimeField(blank=True, null=True)), ("diagnostics", models.JSONField(blank=True, default=dict)), ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pota_import_batches", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="PotaCallsignAttestation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("callsign", models.CharField(max_length=30)), ("attestation_text", models.TextField()), ("attested_at", models.DateTimeField(auto_now_add=True)), ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="callsign_attestations", to="core.potaimportbatch")), ("member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pota_callsign_attestations", to=settings.AUTH_USER_MODEL))], options={"constraints": [models.UniqueConstraint(fields=("batch", "callsign"), name="unique_pota_callsign_attestation")]}),
        migrations.CreateModel(name="PotaActivationImport", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("activation_date", models.DateField()), ("callsign", models.CharField(max_length=30)), ("park_reference", models.CharField(max_length=30)), ("park_name", models.CharField(max_length=200)), ("entity", models.CharField(blank=True, max_length=120)), ("cw_contacts", models.PositiveIntegerField(default=0)), ("data_contacts", models.PositiveIntegerField(default=0)), ("phone_contacts", models.PositiveIntegerField(default=0)), ("total_contacts", models.PositiveIntegerField(default=0)), ("fingerprint", models.CharField(max_length=64, unique=True)), ("location_resolution", models.CharField(choices=[("existing", "Existing Location"), ("unresolved", "Needs Location")], max_length=20)), ("imported_at", models.DateTimeField(auto_now_add=True)), ("adventure", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="pota_import", to="core.adventure")), ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="activations", to="core.potaimportbatch"))], options={"ordering": ["-activation_date", "park_reference"]}),
    ]
