# Generated by Django 6.0.7 on 2026-08-14 07:05

import django.db.models.deletion
from django.db import migrations, models


def associate_existing_imports_with_journals(apps, schema_editor):
    ActivationImport = apps.get_model("core", "PotaActivationImport")
    JournalEntry = apps.get_model("core", "JournalEntry")
    for activation in ActivationImport.objects.filter(journal_entry__isnull=True).iterator():
        journal_id = JournalEntry.objects.filter(adventure_id=activation.adventure_id).order_by("entry_at", "pk").values_list("pk", flat=True).first()
        if journal_id:
            activation.journal_entry_id = journal_id
            activation.save(update_fields=["journal_entry"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_journalentry_primary_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='potaactivationimport',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pota_import', to='core.journalentry'),
        ),
        migrations.RunPython(associate_existing_imports_with_journals, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='potaactivationimport',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pota_imports', to='core.adventure'),
        ),
    ]
