"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qir+59y4#fbt&)yt*tvu=4m(4u(o+b$b((8)ro)p19whf8-mgj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
    "adventures",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.policy_middleware.PolicyAcceptanceMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.google_maps',
                'core.context_processors.account_roles',
                'core.context_processors.organizational_emails',
                'core.context_processors.current_policy_metadata',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    "core.auth_backends.UsernameOrCallsignBackend",
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Google Maps JavaScript API key.
# Preferred: set GOOGLE_MAPS_API_KEY as an environment variable.
# For local development, you may instead place the key by itself in:
# google_maps_api_key.txt
_google_maps_key_file = BASE_DIR / "google_maps_api_key.txt"

GOOGLE_MAPS_API_KEY = os.environ.get(
    "GOOGLE_MAPS_API_KEY",
    "",
).strip()

if not GOOGLE_MAPS_API_KEY and _google_maps_key_file.exists():
    GOOGLE_MAPS_API_KEY = _google_maps_key_file.read_text(
        encoding="utf-8"
    ).strip()

# Server-side address geocoding uses a separate credential from the
# browser-exposed Maps JavaScript key above. Never expose this setting through
# a context processor or template.
_google_geocoding_key_file = BASE_DIR / "google_geocoding_api_key.txt"
GOOGLE_GEOCODING_API_KEY = os.environ.get(
    "GOOGLE_GEOCODING_API_KEY",
    "",
).strip()
if not GOOGLE_GEOCODING_API_KEY and _google_geocoding_key_file.exists():
    GOOGLE_GEOCODING_API_KEY = _google_geocoding_key_file.read_text(
        encoding="utf-8"
    ).strip()

# OpenAI image moderation. Environment configuration takes precedence; a local
# key file is supported only as a development convenience and is gitignored.
_openai_key_file = BASE_DIR / "openai_api_key.txt"
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
if DEBUG and not OPENAI_API_KEY and _openai_key_file.exists():
    OPENAI_API_KEY = _openai_key_file.read_text(encoding="utf-8").strip()

# QRZ XML API credentials. Environment variables are preferred on deployed
# systems; gitignored project-root files are supported for local development.
QRZ_USERNAME = os.environ.get("QRZ_USERNAME", "").strip()
QRZ_PASSWORD = os.environ.get("QRZ_PASSWORD", "").strip()
QRZ_USERNAME_FILE = BASE_DIR / "qrz_username.txt"
QRZ_PASSWORD_FILE = BASE_DIR / "qrz_password.txt"

EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    (
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_USE_TLS", "1") == "1"
EMAIL_USE_SSL = os.environ.get("DJANGO_EMAIL_USE_SSL", "0") == "1"
RADIO_OUTDOORS_CONTACT_EMAIL = os.environ.get(
    "RADIO_OUTDOORS_CONTACT_EMAIL",
    "info@radiooutdoors.org",
).strip()
RADIO_OUTDOORS_ADMIN_EMAIL = os.environ.get(
    "RADIO_OUTDOORS_ADMIN_EMAIL",
    "admin@radiooutdoors.org",
).strip()
DEFAULT_FROM_EMAIL = os.environ.get(
    "DJANGO_DEFAULT_FROM_EMAIL",
    f"Radio Outdoors <{RADIO_OUTDOORS_CONTACT_EMAIL}>",
)
SERVER_EMAIL = os.environ.get(
    "DJANGO_SERVER_EMAIL",
    f"Radio Outdoors System <{RADIO_OUTDOORS_ADMIN_EMAIL}>",
)
ADMINS = [("Radio Outdoors Administrator", RADIO_OUTDOORS_ADMIN_EMAIL)]
RADIO_OUTDOORS_SITE_URL = os.environ.get(
    "RADIO_OUTDOORS_SITE_URL",
    "http://127.0.0.1:8000" if DEBUG else "https://radiooutdoors.org",
).rstrip("/")
ADMIN_NOTIFICATION_SUPPRESSION_SECONDS = int(
    os.environ.get("ADMIN_NOTIFICATION_SUPPRESSION_SECONDS", "3600")
)

PASSWORD_RESET_DOMAIN = os.environ.get("PASSWORD_RESET_DOMAIN", "").strip()
PASSWORD_RESET_USE_HTTPS = (
    os.environ.get("PASSWORD_RESET_USE_HTTPS", "0" if DEBUG else "1") == "1"
)
PASSWORD_RESET_TIMEOUT = int(os.environ.get("PASSWORD_RESET_TIMEOUT", "259200"))
PASSWORD_RESET_RATE_LIMIT = int(
    os.environ.get("PASSWORD_RESET_RATE_LIMIT", "5")
)
PASSWORD_RESET_RATE_LIMIT_WINDOW = int(
    os.environ.get("PASSWORD_RESET_RATE_LIMIT_WINDOW", "900")
)
SMS_RECOVERY_RATE_LIMIT = int(os.environ.get("SMS_RECOVERY_RATE_LIMIT", "5"))
SMS_RECOVERY_VERIFY_LIMIT = int(os.environ.get("SMS_RECOVERY_VERIFY_LIMIT", "8"))
SMS_RECOVERY_RATE_LIMIT_WINDOW = int(
    os.environ.get("SMS_RECOVERY_RATE_LIMIT_WINDOW", "900")
)

# Image moderation is deliberately fail-closed. Configure a real provider class
# implementing ``moderate(image_bytes, content_type=...)`` before expecting
# automatic approvals. The disabled backend leaves every upload Pending Scan.
PHOTO_MODERATION_BACKEND = os.environ.get(
    "PHOTO_MODERATION_BACKEND",
    "core.photo_moderation.OpenAIModerationProvider",
)
OPENAI_MODERATION_MODEL = os.environ.get(
    "OPENAI_MODERATION_MODEL", "omni-moderation-latest"
)
OPENAI_MODERATION_TIMEOUT = int(os.environ.get("OPENAI_MODERATION_TIMEOUT", "20"))
PHOTO_MAX_UPLOAD_BYTES = int(os.environ.get("PHOTO_MAX_UPLOAD_BYTES", str(50 * 1024 * 1024)))
PHOTO_MAX_PROCESSING_BYTES = int(
    os.environ.get("PHOTO_MAX_PROCESSING_BYTES", str(50 * 1024 * 1024))
)
PHOTO_MAX_PIXELS = int(os.environ.get("PHOTO_MAX_PIXELS", "40000000"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "core.qrz_service": {
            "handlers": ["console"],
            "level": os.environ.get("QRZ_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "core.account_views": {
            "handlers": ["console"],
            "level": os.environ.get("QRZ_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "core.photo_moderation": {
            "handlers": ["console"],
            "level": os.environ.get("PHOTO_MODERATION_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

LOGIN_REDIRECT_URL = "/adventures/"
LOGOUT_REDIRECT_URL = "/"
