# Generated by Django 6.0.7 on 2026-08-03 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('adventure_date', models.DateField()),
                ('story', models.TextField()),
                ('radio', models.CharField(blank=True, max_length=100)),
                ('antenna', models.CharField(blank=True, max_length=100)),
                ('modes', models.CharField(blank=True, max_length=100)),
                ('companions', models.CharField(blank=True, help_text='Who were you with?', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to='core.location')),
            ],
            options={
                'ordering': ['-adventure_date', '-created'],
            },
        ),
    ]
