# Generated by Django 6.0.7 on 2026-08-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adventure',
        ),
    ]
