from django.urls import path

from .adif_views import (
    cancel_adif_import,
    confirm_adif_import,
    import_adif,
    preview_adif_import,
)

from .views import (
    add_adventure,
    add_comment,
    add_journal_entry,
    add_operating_position,
    adventure_detail,
    adventure_contacts,
    adventure_journals,
    bulk_delete_adventure_journals,
    adventure_import_contacts,
    all_adventures,
    cancel_adif_import,
    confirm_adif_import,
    create_location,
    create_operating_position_inline,
    delete_comment,
    toggle_journal_visibility,
    toggle_journal_status,
    toggle_adventure_visibility,
    delete_selected_contacts,
    delete_journal_contact,
    delete_adventure,
    delete_journal_entry,
    delete_photo,
    delete_journal_photos,
    edit_adventure,
    edit_journal_entry,
    edit_location,
    edit_operating_position,
    import_adif,
    journal_entry_detail,
    journal_contact_map,
    journal_photo_gallery,
    make_journal_photo,
    make_cover_photo,
    mark_adventure_done,
    mark_adventure_in_progress,
    my_adventures,
    start_adventure_here,
    select_adventure_journals,
    preview_adif_import,
)
from .pota_views import (
    abort_pota_history,
    confirm_pota_history,
    import_pota_history,
    pota_history_result,
    pota_pin_queue,
    retry_pota_pin_lookup,
    review_pota_pin,
    preview_pota_history,
)
from .contact_log_views import (
    add_journal_contact,
    bulk_delete_contacts,
    confirm_pota_hunter_contacts,
    import_pota_hunter_contacts,
    my_contact_log,
    pota_hunter_contact_result,
    preview_pota_hunter_contacts,
    qrz_contact_lookup,
)

urlpatterns = [
    path("", my_adventures, name="my_adventures"),
    path("all/", all_adventures, name="all_adventures"),
    path("add/", add_adventure, name="add_adventure"),
    path("import/pota/", import_pota_history, name="import_pota_history"),
    path("contacts/", my_contact_log, name="my_contact_log"),
    path("contacts/delete-selected/", bulk_delete_contacts, name="bulk_delete_contacts"),
    path("journal/<int:entry_id>/contacts/add/", add_journal_contact, name="add_journal_contact"),
    path("journal/<int:entry_id>/contacts/qrz/", qrz_contact_lookup, name="qrz_contact_lookup"),
    path("journal/<int:entry_id>/contacts/map/", journal_contact_map, name="journal_contact_map"),
    path("journal/<int:entry_id>/contacts/<int:contact_id>/delete/", delete_journal_contact, name="delete_journal_contact"),
    path("contacts/import/pota-hunter/", import_pota_hunter_contacts, name="import_pota_hunter_log"),
    path("contacts/import/pota-hunter/preview/<str:token>/", preview_pota_hunter_contacts, name="preview_pota_hunter_log"),
    path("contacts/import/pota-hunter/confirm/<str:token>/", confirm_pota_hunter_contacts, name="confirm_pota_hunter_log"),
    path("contacts/import/pota-hunter/result/", pota_hunter_contact_result, name="pota_hunter_result"),
    path(
        "import/pota/preview/<str:token>/",
        preview_pota_history,
        name="preview_pota_history",
    ),
    path(
        "import/pota/abort/<str:token>/",
        abort_pota_history,
        name="abort_pota_history",
    ),
    path(
        "import/pota/confirm/<str:token>/",
        confirm_pota_history,
        name="confirm_pota_history",
    ),
    path("import/pota/result/", pota_history_result, name="pota_history_result"),
    path("import/pota/pins/", pota_pin_queue, name="pota_pin_queue"),
    path("import/pota/pins/<int:location_id>/", review_pota_pin, name="review_pota_pin"),
    path("import/pota/pins/<int:location_id>/lookup/", retry_pota_pin_lookup, name="retry_pota_pin_lookup"),
    path(
        "locations/<int:location_id>/start/",
        start_adventure_here,
        name="start_adventure_here",
    ),
    path("locations/create/", create_location, name="create_location"),
    path(
        "locations/<int:location_id>/positions/add/",
        add_operating_position,
        name="add_operating_position",
    ),
    path(
        "positions/<int:position_id>/edit/",
        edit_operating_position,
        name="edit_operating_position",
    ),
    path(
        "locations/<int:location_id>/positions/inline/",
        create_operating_position_inline,
        name="create_operating_position_inline",
    ),
    path(
        "locations/<int:location_id>/edit/",
        edit_location,
        name="edit_location",
    ),
    path("<slug:slug>/comments/add/", add_comment, name="add_comment"),
    path("<slug:slug>/contacts/", adventure_contacts, name="adventure_contacts"),
    path("<slug:slug>/journals/", adventure_journals, name="adventure_journals"),
    path("<slug:slug>/journals/select/", select_adventure_journals, name="select_adventure_journals"),
    path("<slug:slug>/journals/delete-selected/", bulk_delete_adventure_journals, name="bulk_delete_adventure_journals"),
    path(
        "<slug:slug>/contacts/import/",
        adventure_import_contacts,
        name="adventure_import_contacts",
    ),
    path(
        "<slug:slug>/visibility/",
        toggle_adventure_visibility,
        name="toggle_adventure_visibility",
    ),
    path(
        "<slug:slug>/delete/",
        delete_adventure,
        name="delete_adventure",
    ),
    path("comments/<int:comment_id>/delete/", delete_comment, name="delete_comment"),
    path("journal/<int:entry_id>/", journal_entry_detail, name="journal_entry_detail"),
    path("journal/<int:entry_id>/photos/", journal_photo_gallery, name="journal_photo_gallery"),
    path("journal/<int:entry_id>/photos/delete/", delete_journal_photos, name="delete_journal_photos"),
    path("journal/<int:entry_id>/photos/<int:photo_id>/primary/", make_journal_photo, name="make_journal_photo"),
    path("journal/<int:entry_id>/edit/", edit_journal_entry, name="edit_journal_entry"),
    path(
        "journal/<int:entry_id>/visibility/",
        toggle_journal_visibility,
        name="toggle_journal_visibility",
    ),
    path(
        "journal/<int:entry_id>/status/",
        toggle_journal_status,
        name="toggle_journal_status",
    ),
    path(
        "journal/<int:entry_id>/contacts/delete-selected/",
        delete_selected_contacts,
        name="delete_selected_contacts",
    ),
    path(
        "journal/<int:entry_id>/contacts/import/",
        import_adif,
        name="import_adif",
    ),
    path(
        "journal/<int:entry_id>/contacts/preview/<str:token>/",
        preview_adif_import,
        name="preview_adif_import",
    ),
    path(
        "journal/<int:entry_id>/contacts/confirm/<str:token>/",
        confirm_adif_import,
        name="confirm_adif_import",
    ),
    path(
        "journal/<int:entry_id>/contacts/cancel/<str:token>/",
        cancel_adif_import,
        name="cancel_adif_import",
    ),
    path("journal/<int:entry_id>/delete/", delete_journal_entry, name="delete_journal_entry"),
    path("photos/<int:photo_id>/cover/", make_cover_photo, name="make_cover_photo"),
    path("<slug:slug>/photos/<int:photo_id>/cover/", make_cover_photo, name="make_adventure_cover"),
    path("photos/<int:photo_id>/delete/", delete_photo, name="delete_photo"),
    path("<slug:slug>/edit/", edit_adventure, name="edit_adventure"),
    path("<slug:slug>/done/", mark_adventure_done, name="mark_adventure_done"),
    path(
        "<slug:slug>/in-progress/",
        mark_adventure_in_progress,
        name="mark_adventure_in_progress",
    ),
    path(
        "<slug:slug>/journal/add/",
        add_journal_entry,
        name="add_journal_entry",
    ),
    path("<slug:slug>/", adventure_detail, name="adventure_detail"),
]
